Adds batch vaa support
gabzim/wormhole-relayer pull request #3
Opened 2023-03-19 00:35 UTC by gabzim

2023-03-21 19:48 UTC, JoeHowarth requested changes
half done

2023-03-21 19:48 UTC, JoeHowarth commented on relayer/middleware/batch/vaa-to-log.utils.ts
> +export async function findLogFromVaa(
This will likely need to be more robust unless we're fine with the whole workflow failing and retrying several times

2023-03-21 19:48 UTC, JoeHowarth commented on relayer/middleware/batch/batch-vaa.middleware.ts
> +    const batchLogs = vaaLogs.filter((l) => l.args.nonce != 0);
The nonce has to be equal for all vaas inside the batch, so this should be `ctx.vaa.nonce === l.args.nonce`

2023-03-21 19:48 UTC, JoeHowarth commented on relayer/middleware/batch/batch-builder.helper.ts
> +    const vaas = Object.values(this.fetchedVaas);
Maybe put some validation here to catch cases where it is 'built' with invalid/missing data?

2023-03-25 18:37 UTC, gabzim commented
Closing in favor of new approaches for GR.

2023-03-25 18:37 UTC, closed without merging